# Generated by Django 2.2.6 on 2019-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191115_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], max_length=1, null=True),
        ),
    ]
