# Generated by Django 2.2.6 on 2019-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='men', max_length=1, null=True),
        ),
    ]
