# Generated by Django 2.2.6 on 2019-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191203_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='women', max_length=12, null=True),
        ),
    ]
